apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: recipes
data:
  DEFAULT_PASSWORD: "{{DEFAULT_PASSWORD}}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: recipes
data:
  DEFAULT_EMAIL: "mealie@carstens.tech"
  TZ: "Europe/Zurich"
  TOKEN_TIME: "24"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: recipes
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hkotel/mealie:v0.4.3
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: backend-secret
          - configMapRef:
              name: backend-config
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: "/app/data"
            name: "sqlite-data"
      volumes:
      - name: sqlite-data
        persistentVolumeClaim:
          claimName: mealie-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-db
  namespace: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
