apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  DEFAULT_PASSWORD: "{{ .Values.secret.password }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  DEFAULT_EMAIL: "{{ .Values.configmap.email }}"
  TZ: "{{ .Values.configmap.timezone }}"
  TOKEN_TIME: "{{ .Values.configmap.tokenTime }}"
