name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v1
      - name: update password in manifest.yml
        run: sed -i -e "s#{{DEFAULT_PASSWORD}}#${{ secrets.DEFAULT_PASSWORD }}#g" .kubernetes/manifest.yaml
      - uses: danielr1996/kubectl-action@1.0.0
        name: apply config
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -f .kubernetes/manifest.yaml
